export const SEND_MESSAGE = 'SEND_MESSAGE';

export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const ADD_POST = 'ADD_POST';
export const SET_PROFILE_IS_LOADING = 'SET_PROFILE_IS_LOADING';
export const SET_USER_STATUS = 'SET_USER_STATUS';

export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const TOGGLE_FOLLOWING_IN_PROGRESS = 'TOGGLE_FOLLOWING_IN_PROGRESS';

export const SET_USER_AUTH = 'SET_USER_AUTH';

export const INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS';