export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CHANGE_NEW_MESSAGE_TEXT = 'CHANGE_NEW_MESSAGE_TEXT';

export const ADD_POST = 'ADD_POST';
export const CHANGE_NEW_POST_TEXT = 'CHANGE_NEW_POST_TEXT';

export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';